{% set name = "notion-client" %}
{% set version = "2.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/notion-client-{{ version }}.tar.gz
  sha256: 3827e381ccb5a21aeb606686787edfb6c7a10681cb3507c4d606a1918e791061

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - httpx >=0.15.0
    - python >={{ python_min }}

test:
  imports:
    - notion_client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ramnes/notion-sdk-py
  summary: Python client for the official Notion API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
    - pavel
