{% set name = "notion-client" %}
{% set version = "2.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/notion-client-{{ version }}.tar.gz
  sha256: c4b4ae04ce182eb89611d41544dac710049683a4d7309c4b22fde52f81cbcb39

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - httpx >=0.15.0
    - python >=3.7

test:
  imports:
    - notion_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ramnes/notion-sdk-py
  summary: Python client for the official Notion API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
    - pavel
